Repository puppetlabs/puppetlabs-apache, pull requests merged in 2018-12, with the labels that each got.

#1855 (maint) Add Ubuntu 14.04 back to the supported modules list
  metadata.json
Labels: maintenance

#1856 (FM-7605) - Disabling conf_enabled on Ubuntu 18.04 by default as it conflicts with Shibboleth causing errors with apache2.
  manifests/params.pp
Labels: bugfix

#1822 SCL support for httpd and php7.1
  README.md
  manifests/mod/php.pp
  manifests/params.pp
  manifests/version.pp
  spec/acceptance/zzz_centos_scl_spec.rb
Labels: feature

#1858 (MODULES-8374) - Release Prep 3.5.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1860 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#1861 (maint) - 3.5.0 Mergeback
  CHANGELOG.md
  README.md
  metadata.json
Labels: maintenance

#1746 default server_tokens to prod - more secure default
  README.md
  manifests/init.pp
Labels: backwards-incompatible

#1862 (Modules 8141/Modules 8379) - Addition of support for SLES 15
  manifests/params.pp
  metadata.json
  spec/acceptance/apache_parameters_spec.rb
  spec/acceptance/class_spec.rb
  spec/acceptance/default_mods_spec.rb
  spec/acceptance/itk_spec.rb
  spec/acceptance/mod_dav_svn_spec.rb
  spec/acceptance/mod_deflate_spec.rb
  spec/acceptance/mod_mime_spec.rb
  spec/acceptance/mod_negotiation_spec.rb
  spec/acceptance/mod_passenger_spec.rb
  spec/acceptance/mod_php_spec.rb
  spec/acceptance/mod_proxy_html_spec.rb
  spec/acceptance/mod_security_spec.rb
  spec/acceptance/prefork_worker_spec.rb
  spec/acceptance/vhost_spec.rb
  spec/spec_helper_acceptance.rb
Labels: feature

#1866 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix

#1863 (maint) Add HTML anchor tag
  README.md
Labels: maintenance
