Repository puppetlabs/puppetlabs-apache, pull requests merged in 2019-09, with the labels that each got.

#1941 FM-8140 Add Redhat 8 support
  metadata.json
  provision.yaml
  spec/acceptance/apache_parameters_spec.rb
  spec/acceptance/class_spec.rb
  spec/acceptance/default_mods_spec.rb
  spec/acceptance/itk_spec.rb
  spec/acceptance/prefork_worker_spec.rb
  spec/acceptance/vhost_spec.rb
  spec/classes/mod/passenger_spec.rb
  spec/classes/mod/security_spec.rb
  spec/defines/fastcgi_server_spec.rb
  spec/defines/vhost_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#1946 MODULES-9083: remove double quotes to allow flags in SSLCARevocationCheck
  spec/acceptance/apache_ssl_spec.rb
  templates/vhost/_ssl.erb
Labels: maintenance

#1928 Add LDAPReferrals configuration parameter
  spec/defines/vhost_spec.rb
  templates/vhost/_directories.erb
Labels: feature

#1948 (MODULES-9863) 5.1.0 release prep
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1949 (MODULES-9867) - Release Merge back v5.1.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1947 add possibility to define variables inside VirtualHost definition
  manifests/vhost.pp
  templates/vhost/_file_footer.erb
  templates/vhost/_file_header.erb
Labels: feature

#1939 Add shibboleth support for Debian 10
  manifests/params.pp
Labels: bugfix

#1952 (maint) Add a codeowners file
  CODEOWNERS
Labels: maintenance

#1942 Add owner, group, file_mode and show_diff to apache::custom_config
  manifests/custom_config.pp
Labels: bugfix

#1955 use full path for proxy host in test
  spec/acceptance/vhost_spec.rb
Labels: maintenance
