Repository puppetlabs/puppetlabs-apache, pull requests merged in 2019-04, with the labels that each got.

#1881 MODULES-8541 : Allow HostnameLookups to be modified
  README.md
  manifests/init.pp
  manifests/params.pp
  spec/acceptance/apache_parameters_spec.rb
  spec/classes/apache_spec.rb
  spec/defines/vhost_spec.rb
  templates/httpd.conf.erb
Labels: feature

#1901 (MODULES-8837) - 4.1.0 Release Prep
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1903 (MODULES-8837) - Prep Fix
  CHANGELOG.md
Labels: maintenance

#1904 (MODULES-8841) - Release Merge back 4.1.0
  CHANGELOG.md
  README.md
  metadata.json
Labels: maintenance

#1908 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#1914 (MODULES-8931) Fix stahnma/epel failures
  spec/spec_helper_acceptance.rb
Labels: bugfix

#1912 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#1885 Logging bug: prevent upcoming log events from getting lost
  manifests/vhost.pp
Labels: maintenance

#1893 Define SCL package name for mod_ldap
  manifests/params.pp
  spec/classes/mod/authnz_ldap_spec.rb
  spec/classes/mod/ldap_spec.rb
Labels: needs-rebase

#1878 Additional commands to detect Apache version and regexp check
  lib/facter/apache_version.rb
  spec/unit/apache_version_spec.rb
Labels: maintenance
