Repository puppetlabs/puppetlabs-apache, pull requests merged in 2019-02, with the labels that each got.

#1847 Added WSGI Options WSGIApplicationGroup and WSGIPythonOptimize
  README.md
  manifests/mod/wsgi.pp
  spec/classes/mod/wsgi_spec.rb
  templates/mod/wsgi.conf.erb
  templates/vhost/_wsgi.erb
Labels: feature

#1883 Typo: add missing comma in example snippet
  README.md
Labels: maintenance

#1882 Manage all mod_remoteip parameters supported by Apache
  manifests/mod/remoteip.pp
  spec/classes/mod/remoteip_spec.rb
  templates/mod/remoteip.conf.epp
  templates/mod/remoteip.conf.erb
Labels: needs-docs

#1886 (maint) - Removing dead link
  README.md
Labels: maintenance

#1852 Added code to paramertize the libphp prefix
  manifests/mod/php.pp
Labels: feature, needs-docs, needs-tests

#1887 Update README to include new param for mod::php
  README.md
Labels: maintenance
