Repository puppetlabs/puppetlabs-apache, pull requests merged in 2019-12, with the labels that each got.

#1981 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#1982 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#1983 Add Github Actions release workflow
  .github/workflows/release.yml
Labels: maintenance

#1984 Fix newline being added before proxy params
  spec/defines/vhost_spec.rb
  templates/vhost/_directories.erb
Labels: bugfix

#1985 (maint) Release Mergeback version v5.3.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1980 Add an apache::vhost::fragment define
  manifests/vhost/fragment.pp
  spec/defines/vhost_fragment_spec.rb
Labels: feature

#1986 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance
