Repository puppetlabs/puppetlabs-apache, pull requests merged in 2019-11, with the labels that each got.

#1966 (maint) FM-8656 minor fix for sles
  spec/acceptance/vhost_spec.rb
Labels: maintenance

#1971 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#1974 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#1973 (FM-8721) fix php version and ssl error on redhat8
  manifests/mod/ssl.pp
  manifests/params.pp
  spec/acceptance/mod_php_spec.rb
  spec/acceptance/vhost_spec.rb
  spec/classes/mod/php_spec.rb
Labels: bugfix

#1977 (FM-8672) - Addition of Support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#1976 move unless into manage_security_corerules
  manifests/mod/security.pp
Labels: bugfix

#1975 Change mod_proxy's ProxyTimeout to follow Apache's global timeout
  manifests/mod/proxy.pp
  templates/mod/proxy.conf.erb
Labels: bugfix

#1978 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  metadata.json
Labels: maintenance
