Repository puppetlabs/puppetlabs-apache, pull requests merged in 2019-03, with the labels that each got.

#1890 pdksync - Remove .project from .gitignore
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .sync.yml
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1895 (bugfix) set kernel for facter version test
  spec/unit/apache_version_spec.rb
Labels: bugfix

#1898 (feat) - Amazon Linux 2 compatibility added
  manifests/default_mods.pp
  manifests/mod.pp
  manifests/params.pp
Labels: feature

#1897 (L10n) Updating translations for readmes/README_ja_JP.md
  readmes/README_ja_JP.md
Labels: maintenance

#1896 FM-7782 - cleanup
  README.md
  spec/acceptance/apache_parameters_spec.rb
  spec/acceptance/class_spec.rb
  spec/acceptance/default_mods_spec.rb
  spec/acceptance/init_task_spec.rb
  spec/acceptance/itk_spec.rb
  spec/acceptance/mod_dav_svn_spec.rb
  spec/acceptance/mod_deflate_spec.rb
  spec/acceptance/mod_fcgid_spec.rb
  spec/acceptance/mod_mime_spec.rb
  spec/acceptance/mod_negotiation_spec.rb
  spec/acceptance/mod_pagespeed_spec.rb
  spec/acceptance/mod_passenger_spec.rb
  spec/acceptance/mod_php_spec.rb
  spec/acceptance/mod_proxy_html_spec.rb
  spec/acceptance/mod_security_spec.rb
  spec/acceptance/prefork_worker_spec.rb
  spec/acceptance/vhost_spec.rb
  spec/acceptance/zzz_centos_scl_spec.rb
  spec/classes/mod/dav_svn_spec.rb
  spec/classes/mod/deflate_spec.rb
  spec/classes/mod/mime_spec.rb
  spec/classes/mod/passenger_spec.rb
  spec/classes/mod/php_spec.rb
  spec/spec_helper_acceptance.rb
Labels: maintenance

#1900 (MODULES-7196) Allow setting CASRootProxiedAs per virtualhost (replaces #1857)
  README.md
  manifests/vhost.pp
  spec/classes/mod/auth_cas_spec.rb
Labels: feature
