Repository puppetlabs/puppetlabs-apache, pull requests merged in 2020-01, with the labels that each got.

#1992 pdksync - (FM-8581) - Debian 10 added to travis and provision file refactored
  .sync.yml
  .travis.yml
  provision.yaml
Labels: feature

#1990 (MODULES-10391) ssl_protocol includes SSLv2 and SSLv3 on all platforms
  REFERENCE.md
  manifests/mod/ssl.pp
  manifests/params.pp
  spec/acceptance/apache_ssl_spec.rb
  spec/classes/mod/ssl_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: bugfix

#1993 Mergeback release version v5.4.0
  CHANGELOG.md
  REFERENCE.md
  manifests/mod/ssl.pp
  metadata.json
Labels: maintenance

#1991 (MODULES-10360) Fix icon paths for RedHat systems
  manifests/mod/autoindex.pp
  templates/mod/autoindex.conf.erb
Labels: bugfix

#1988 Add template variables and parameters for ModSecurity Audit Logs
  manifests/mod/security.pp
  manifests/params.pp
  spec/classes/mod/security_spec.rb
  templates/mod/security.conf.erb
Labels: feature

#1994 Fix proxy_html Module to work on Debian 10
  manifests/mod/proxy_html.pp
Labels: bugfix
