Repository puppetlabs/puppetlabs-apache, pull requests merged in 2020-04, with the labels that each got.

#2017 Changed the apache-mod-ldap.conf title to ldap.conf
  manifests/mod/ldap.pp
  spec/classes/mod/ldap_spec.rb
Labels: bugfix, maintenance

#2014 Add ProxyIOBufferSize option
  manifests/mod/proxy.pp
  templates/mod/proxy.conf.erb
Labels: feature

#2018 Fix template conditional
  templates/mod/proxy.conf.erb
Labels: maintenance
