Repository puppetlabs/puppetlabs-apache, pull requests merged in 2020-09, with the labels that each got.

#2062 pdksync - (feat) - Removal of inappropriate terminology
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  CONTRIBUTING.md
  README.md
  REFERENCE.md
  manifests/balancer.pp
  manifests/balancermember.pp
  manifests/mod/info.pp
  metadata.json
  readmes/README_ja_JP.md
  spec/util/_resources/test_metadata_json.rb
Labels: bugfix

#2063 Configure default shared lib path for mod_wsgi on RHEL8
  manifests/params.pp
  spec/classes/mod/wsgi_spec.rb
Labels: feature

#2065 (maint) Use 'policycoreutils-python-utils' on RHEL 8
  README.md
  spec/acceptance/apache_parameters_spec.rb
  spec/acceptance/class_spec.rb
Labels: maintenance

#2067 (maint) Use 'policycoreutils-python-utils' on RHEL 8
  spec/acceptance/vhost_spec.rb
Labels: maintenance

#2069 Fix typos including consecutive occurrences of 'the'
  README.md
  REFERENCE.md
  manifests/mod/ldap.pp
Labels: maintenance

#2070 Replace some occurrences of non-ASCII chars
  manifests/mod/jk.pp
  manifests/vhost.pp
Labels: maintenance
