Repository puppetlabs/puppetlabs-apache, pull requests merged in 2020-12, with the labels that each got.

#2101 pdksync - (feat) - Bump Puppet boundary
  metadata.json
Labels: feature

#2103 (MODULES-10887) Set `use_servername_for_filenames` for defaults
  manifests/init.pp
Labels: feature

#2102 Fix bool2httpd function call for older ruby versions
  lib/puppet/functions/apache/bool2httpd.rb
Labels: bugfix

#2104 (fix) Convert unnecessary multi line warnings to single lines
  templates/mod/_require.erb
Labels: bugfix

#2105 Release version 5.8.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#2107 pdksync - Remove EL6 testing from Travis
  provision.yaml
Labels: maintenance

#2090 Add support for mod_md
  manifests/mod/md.pp
  manifests/mod/watchdog.pp
  manifests/params.pp
  manifests/vhost.pp
  spec/acceptance/mod_md_spec.rb
  spec/classes/mod/md_spec.rb
  spec/classes/mod/watchdog_spec.rb
  spec/defines/vhost_spec.rb
  templates/mod/md.conf.epp
  templates/vhost/_file_header.erb
  templates/vhost/_ssl.erb
Labels: feature
