Repository puppetlabs/puppetlabs-apache, pull requests merged in 2020-02, with the labels that each got.

#1987 (MODULES-10432) Add mod_auth_openidc support
  manifests/mod/auth_openidc.pp
  manifests/params.pp
  manifests/vhost.pp
  spec/acceptance/vhost_spec.rb
  spec/classes/mod/auth_openidc_spec.rb
  spec/defines/vhost_spec.rb
  templates/vhost/_auth_oidc.erb
  types/oidcsettings.pp
Labels: feature

#1998 (IAC-365) updating tokens and dataset for honeycomb
  .github/workflows/release.yml
  .sync.yml
  .travis.yml
  Gemfile
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1999 Use ldap_trusted_mode in conditional
  templates/httpd.conf.erb
Labels: bugfix

#2003 pdksync - Add weekly scheduled workflows
  .github/workflows/weekly.yml
  .travis.yml
  spec/classes/mod/php_spec.rb
Labels: maintenance

#2008 pdksync - (maint) - Pdk Update
  .travis.yml
  metadata.json
Labels: maintenance
