Repository puppetlabs/puppetlabs-apache, pull requests merged in 2021-01, with the labels that each got.

#2093 Add ssl_user_name vhost parameter
  manifests/vhost.pp
  spec/acceptance/vhost_spec.rb
  spec/defines/vhost_spec.rb
  templates/vhost/_ssl.erb
Labels: feature

#2114 (MAINT) Perform pdk update
  .sync.yml
  Rakefile
Labels: maintenance

#2111 (FIX) Correct PHP packages on Ubuntu 16.04
  manifests/params.pp
Labels: bugfix

#2116 (MAINT) Release prep for v5.9.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#2117 (IAC-1402) Release mergeback v5.9.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#2112 Use the correct matches in rspec
  spec/classes/apache_spec.rb
  spec/classes/mod/authnz_ldap_spec.rb
  spec/classes/mod/data_spec.rb
  spec/classes/mod/peruser_spec.rb
  spec/classes/mod/php_spec.rb
  spec/classes/mod/remoteip_spec.rb
  spec/classes/mod/ssl_spec.rb
  spec/classes/mod/status_spec.rb
  spec/classes/mod/wsgi_spec.rb
Labels: maintenance

#2118 pdksync - Update gha templates
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  .travis.yml
  Rakefile
  metadata.json
Labels: maintenance
