Repository puppetlabs/puppetlabs-apache, pull requests merged in 2021-03, with the labels that each got.

#2125 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .sync.yml
  .travis.yml
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#2136 v6.0.0 Release Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance

#2129 Drop Ubuntu 10.04 compatibility code
  README.md
  REFERENCE.md
  manifests/mod/ssl.pp
  manifests/params.pp
  readmes/README_ja_JP.md
Labels: maintenance

#2138 Fix HEADER* and README* wildcards in IndexIgnore
  templates/mod/autoindex.conf.erb
Labels: bugfix

#2139 pdksync - PDK Update - Replace Travis and Appveyor with Github Actions
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance
