Repository puppetlabs/puppetlabs-apache, pull requests merged in 2021-06, with the labels that each got.

#2156 pdksync - (maint) PDKSync - PDK Update
  .github/workflows/auto_release.yml
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#2142 The default disk_cache.conf.erb caches everything.
  manifests/mod/disk_cache.pp
  spec/classes/mod/disk_cache_spec.rb
  templates/mod/disk_cache.conf.erb
Labels: feature

#2158 Update the default version of Apache for Amazon Linux 2
  manifests/mod/passenger.pp
  manifests/version.pp
Labels: bugfix

#2154 Only warn about servername logging if relevant
  manifests/vhost.pp
Labels: bugfix

#2159 Release version 6.3.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
