Repository puppetlabs/puppetlabs-apache, pull requests merged in 2021-02, with the labels that each got.

#2122 (IAC-1186) Add $use_port_for_filenames parameter
  manifests/init.pp
  manifests/vhost.pp
  manifests/vhost/fragment.pp
  spec/acceptance/apache_ssl_spec.rb
  spec/acceptance/vhost_spec.rb
  spec/defines/vhost_fragment_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#2121 (MODULES-10899) Handle PHP8 MOD package naming convention changes
  manifests/mod/php.pp
  manifests/params.pp
  spec/acceptance/mod_php_spec.rb
  spec/classes/mod/php_spec.rb
Labels: bugfix

#2126 (IAC-1467) Release prep for version v5.10.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#2127 (IAC-1467) Mergeback PR v5.10.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#2130 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance

#2132 pdksync - (MAINT) Remove SLES 11 support
  metadata.json
Labels: maintenance

#2134 pdksync - (MAINT) PDK update for GHA workflows + Litmus updates
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  .travis.yml
  metadata.json
Labels: maintenance

#2133 (MAINT) Adjust $use_servername_for_filenames behaviour change timeline
  manifests/vhost.pp
Labels: maintenance
