Repository puppetlabs/puppetlabs-apache, pull requests merged in 2021-07, with the labels that each got.

#2166 (MODULES-10899) Load php module with the right libphp file
  manifests/mod/php.pp
  spec/classes/mod/php_spec.rb
Labels: bugfix

#2168 pdksync - (maint) - Updating Contribution Guidelines
  CONTRIBUTING.md
Labels: maintenance

#2165 (maint) Fix puppet-strings docs on apache::vhost
  REFERENCE.md
  manifests/vhost.pp
Labels: bugfix

#2172 (maint) Release Prep v6.3.1
  CHANGELOG.md
  metadata.json
Labels: maintenance

#2173 (maint) Release Merge Back PR v6.3.1
  CHANGELOG.md
  metadata.json
Labels: maintenance

#2164 Allow custom userdir directives
  REFERENCE.md
  manifests/mod/userdir.pp
  spec/classes/mod/userdir_spec.rb
  templates/mod/userdir.conf.erb
Labels: feature

#2174 (MODULES-11075) Improve future version handling for RHEL
  manifests/params.pp
Labels: feature

#2157 Add feature to reload apache service when content of ssl files has changed
  REFERENCE.md
  manifests/init.pp
  manifests/mod/ssl.pp
  manifests/mod/ssl/reload.pp
  manifests/params.pp
  manifests/vhost.pp
  spec/acceptance/apache_ssl_spec.rb
  spec/classes/mod/ssl_spec.rb
  spec/defines/vhost_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature
