Repository puppetlabs/puppetlabs-apache, pull requests merged in 2021-09, with the labels that each got.

#2186 Debian 11: fix typo in `versioncmp()` / set default php to 7.4
  manifests/params.pp
  spec/classes/mod/php_spec.rb
Labels: bugfix

#2190 (FM-8483) reenable the testcases
  spec/acceptance/apache_parameters_spec.rb
  spec/acceptance/class_spec.rb
  spec/acceptance/default_mods_spec.rb
  spec/acceptance/itk_spec.rb
  spec/acceptance/prefork_worker_spec.rb
  spec/acceptance/vhost_spec.rb
Labels: maintenance

#2189 Drop Debian < 8 and Ubuntu < 14.04 code
  manifests/mod/suphp.pp
  manifests/mpm.pp
  manifests/params.pp
  manifests/version.pp
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible

#2193 Restore Ubuntu 14.04 support in suphp
  manifests/mod/suphp.pp
Labels: bugfix

#2123 Drop support for Debian < 9
  manifests/dev.pp
  manifests/mod/suphp.pp
  manifests/params.pp
  metadata.json
  spec/classes/apache_spec.rb
  spec/classes/mod/alias_spec.rb
  spec/classes/mod/auth_cas_spec.rb
  spec/classes/mod/auth_gssapi_spec.rb
  spec/classes/mod/auth_kerb_spec.rb
  spec/classes/mod/auth_mellon_spec.rb
  spec/classes/mod/auth_openidc_spec.rb
  spec/classes/mod/authn_dbd_spec.rb
  spec/classes/mod/authnz_ldap_spec.rb
  spec/classes/mod/authnz_pam_spec.rb
  spec/classes/mod/data_spec.rb
  spec/classes/mod/dav_svn_spec.rb
  spec/classes/mod/deflate_spec.rb
  spec/classes/mod/dev_spec.rb
  spec/classes/mod/dir_spec.rb
  spec/classes/mod/disk_cache_spec.rb
  spec/classes/mod/dumpio_spec.rb
  spec/classes/mod/event_spec.rb
  spec/classes/mod/expires_spec.rb
  spec/classes/mod/ext_filter_spec.rb
  spec/classes/mod/fcgid_spec.rb
  spec/classes/mod/http2_spec.rb
  spec/classes/mod/info_spec.rb
  spec/classes/mod/intercept_form_submit_spec.rb
  spec/classes/mod/itk_spec.rb
  spec/classes/mod/jk_spec.rb
  spec/classes/mod/ldap_spec.rb
  spec/classes/mod/lookup_identity.rb
  spec/classes/mod/mime_magic_spec.rb
  spec/classes/mod/mime_spec.rb
  spec/classes/mod/negotiation_spec.rb
  spec/classes/mod/pagespeed_spec.rb
  spec/classes/mod/perl_spec.rb
  spec/classes/mod/php_spec.rb
  spec/classes/mod/prefork_spec.rb
  spec/classes/mod/proxy_balancer_spec.rb
  spec/classes/mod/proxy_html_spec.rb
  spec/classes/mod/python_spec.rb
  spec/classes/mod/remoteip_spec.rb
  spec/classes/mod/reqtimeout_spec.rb
  spec/classes/mod/rpaf_spec.rb
  spec/classes/mod/shib_spec.rb
  spec/classes/mod/speling_spec.rb
  spec/classes/mod/ssl_spec.rb
  spec/classes/mod/status_spec.rb
  spec/classes/mod/userdir_spec.rb
  spec/classes/mod/worker_spec.rb
  spec/classes/mod/wsgi_spec.rb
  spec/classes/params_spec.rb
  spec/classes/service_spec.rb
  spec/defines/balancer_spec.rb
  spec/defines/balancermember_spec.rb
  spec/defines/custom_config_spec.rb
  spec/defines/mod_spec.rb
  spec/defines/vhost_custom_spec.rb
  spec/spec_helper_local.rb
Labels: backwards-incompatible

#2191 add double quote on scope parameter
  templates/vhost/_auth_oidc.erb
Labels: bugfix
