Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-05, with the labels that each got.

#2206 init.pp: fix typo in purge_vdir documentation
  manifests/init.pp
Labels: community, stale

#2212 mod_auth_gssapi: Add support for `GssapiBasicAuth`.
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
  templates/vhost/_gssapi.epp
Labels: community

#2238 Drop support for Fedora < 18
  manifests/version.pp
  spec/classes/apache_spec.rb
  spec/classes/mod/wsgi_spec.rb
  spec/spec_helper_local.rb
Labels: bugfix, community

#2236 pdksync - (MAINT) Stale bot config/msg update
  .github/workflows/stale.yml
Labels: maintenance

#2222 apache::vhost ProxyPassMatch in Location containers
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
  templates/vhost/_directories.erb
Labels: feature, community
