Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-12, with the labels that each got.

#2346 Remove executable bit from various files
  README.md
  manifests/init.pp
  templates/httpd.conf.erb
Labels: community

#2320 Clean up SELinux handling in acceptance testing.
  spec/acceptance/apache_parameters_spec.rb
  spec/acceptance/class_spec.rb
  spec/acceptance/vhost_spec.rb
  spec/setup_acceptance_node.pp
Labels: maintenance, community

#2345 add LimitRequestLine parameter
  manifests/init.pp
  spec/acceptance/apache_parameters_spec.rb
  templates/httpd.conf.erb
Labels: community

#2339 remove _module from apache::mod::unique_id name.
  manifests/mod/security.pp
  spec/classes/mod/security_spec.rb
Labels: community

#2349 disable::mpm_event: Fix module deactivation
  manifests/mpm/disable_mpm_event.pp
  spec/classes/apache_spec.rb
Labels: bugfix, community

#2355 fix mod_proxy_html on FreeBSD
  manifests/params.pp
  spec/classes/mod/proxy_html_spec.rb
Labels: bugfix, community

#2356 pdksync - (MAINT) Remove stalebot
  .github/workflows/stale.yml
Labels: maintenance

#2350 Drop deprecated a2mod type/providers
  lib/puppet/provider/a2mod/a2mod.rb
  lib/puppet/provider/a2mod/gentoo.rb
  lib/puppet/provider/a2mod/modfix.rb
  lib/puppet/provider/a2mod/redhat.rb
  lib/puppet/type/a2mod.rb
  spec/unit/provider/a2mod/gentoo_spec.rb
Labels: backwards-incompatible, community

#2359 (GH-2291) Further refine types
  manifests/mod/auth_cas.pp
  manifests/mod/proxy.pp
Labels: backwards-incompatible

#2362 (CONT-406) Fix for RHEL 7 compatibility
  templates/mod/security.conf.erb
  templates/mod/security_crs.conf.erb
Labels: bugfix
