Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-09, with the labels that each got.

#2280 Parameterize CRS DOS protection
  manifests/mod/security.pp
  spec/classes/mod/security_spec.rb
  templates/mod/security_crs.conf.erb
Labels: community

#2265 Allow multiple scopes for Scope in Apache::OIDCSettings
  types/oidcsettings.pp
Labels: feature, community

#2300 Test proxy_dest_reverse_match parameter
  spec/defines/vhost_spec.rb
Labels: maintenance, community

#2303 Simplify the logic in _require.erb
  templates/vhost/_require.erb
Labels: community

#2301 Allow RewriteInherit with empty rewrites
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
Labels: community

#2309 (maint) Add variable manage_vhost_enable_dir
  manifests/init.pp
Labels: bugfix

#2317 Revert "(MAINT) Removing support for CentOS 8"
  metadata.json
Labels: maintenance

#2313 (maint) Codebase Hardening
  manifests/custom_config.pp
  manifests/init.pp
  manifests/mpm/disable_mpm_event.pp
  manifests/mpm/disable_mpm_prefork.pp
  manifests/mpm/disable_mpm_worker.pp
  manifests/params.pp
  spec/defines/custom_config_spec.rb
Labels: bugfix
