Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-10, with the labels that each got.

#2322 pdksync - (CONT-130) Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#2324 pdksync - (PDKSync) Removal of puppet_module_gems
  Gemfile
  Rakefile
  metadata.json
Labels: maintenance, hacktoberfest

#2326 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
  spec/classes/apache_spec.rb
  spec/classes/mod/alias_spec.rb
  spec/classes/mod/auth_cas_spec.rb
  spec/classes/mod/auth_gssapi_spec.rb
  spec/classes/mod/auth_kerb_spec.rb
  spec/classes/mod/auth_mellon_spec.rb
  spec/classes/mod/auth_openidc_spec.rb
  spec/classes/mod/authn_dbd_spec.rb
  spec/classes/mod/cluster_spec.rb
  spec/classes/mod/dav_svn_spec.rb
  spec/classes/mod/deflate_spec.rb
  spec/classes/mod/dev_spec.rb
  spec/classes/mod/dir_spec.rb
  spec/classes/mod/disk_cache_spec.rb
  spec/classes/mod/event_spec.rb
  spec/classes/mod/ext_filter_spec.rb
  spec/classes/mod/fcgid_spec.rb
  spec/classes/mod/info_spec.rb
  spec/classes/mod/intercept_form_submit_spec.rb
  spec/classes/mod/itk_spec.rb
  spec/classes/mod/jk_spec.rb
  spec/classes/mod/ldap_spec.rb
  spec/classes/mod/lookup_identity.rb
  spec/classes/mod/mime_magic_spec.rb
  spec/classes/mod/mime_spec.rb
  spec/classes/mod/pagespeed_spec.rb
  spec/classes/mod/perl_spec.rb
  spec/classes/mod/prefork_spec.rb
  spec/classes/mod/proxy_balancer_spec.rb
  spec/classes/mod/proxy_html_spec.rb
  spec/classes/mod/python_spec.rb
  spec/classes/mod/reqtimeout_spec.rb
  spec/classes/mod/shib_spec.rb
  spec/classes/mod/speling_spec.rb
  spec/classes/mod/ssl_spec.rb
  spec/classes/mod/status_spec.rb
  spec/classes/mod/worker_spec.rb
  spec/classes/mod/wsgi_spec.rb
  spec/classes/vhosts_spec.rb
  spec/defines/mod_spec.rb
  spec/defines/vhost_custom_spec.rb
  spec/spec_helper_local.rb
Labels: bugfix, hacktoberfest

#2312 fix directory empty options if an empty array is being used
  spec/acceptance/vhost_spec.rb
  templates/vhost/_directories.erb
Labels: community

#2338 Make serveradmin an optional parameter and use it
  manifests/init.pp
  spec/classes/apache_spec.rb
  templates/httpd.conf.erb
Labels: community

#2335 Support setting SSLProxyCipherSuite on mod_ssl
  manifests/mod/ssl.pp
  spec/classes/mod/ssl_spec.rb
  templates/mod/ssl.conf.erb
Labels: feature, community

#2337 Automatically enable mod_http2 if needed
  manifests/init.pp
  manifests/vhost.pp
Labels: community

#2336 Update EL8+ and Debian SSL defaults
  manifests/mod/ssl.pp
  manifests/params.pp
  spec/acceptance/apache_ssl_spec.rb
  spec/classes/mod/ssl_spec.rb
  templates/mod/ssl.conf.erb
Labels: feature, community

#2340 Extract acceptance node setup to a separate file
  spec/setup_acceptance_node.pp
  spec/spec_helper_acceptance_local.rb
Labels: community

#2333 Fix RedHat + PHP 8 libphp file
  manifests/mod/php.pp
  spec/classes/mod/php_spec.rb
Labels: community
