Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-06, with the labels that each got.

#2169 Add an apache::vhost::proxy define
  manifests/vhost/custom.pp
  manifests/vhost/fragment.pp
  manifests/vhost/proxy.pp
  spec/defines/vhost_proxy_spec.rb
  types/vhost/proxypass.pp
Labels: community, stale

#2240 Let limitreqfieldsize and limitreqfields be integers
  manifests/init.pp
Labels: community

#2214 mod_auth_gssapi: Add support for every configuration directive
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
  templates/vhost/_gssapi.epp
Labels: feature, community

#2243 Acceptance tests: correct EPEL usage
  spec/acceptance/mod_authnz_ldap_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: community

#2249 (MODULES-11329) Typo fix
  README.md
Labels: maintenance

#2253 Use a stricter data type on apache::vhost::aliases
  manifests/vhost.pp
  spec/acceptance/default_mods_spec.rb
  spec/defines/vhost_spec.rb
  templates/vhost/_aliases.erb
Labels: community

#2254 Clean up includes and templates in vhost.pp
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
  templates/vhost/_scriptalias.erb
  templates/vhost/_serveralias.erb
  templates/vhost/_setenv.erb
Labels: feature, community

#2256 Group assertions in vhost spec
  spec/defines/vhost_spec.rb
Labels: community

#2257 Correct vhost parameter documentation and run vhost tests on all supported OSes
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
Labels: maintenance, community
