Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-04, with the labels that each got.

#2227 Restructure MPM disabling
  manifests/mpm.pp
Labels: community

#2226 Drop Apache 2.0 compatibility code
  manifests/mod/proxy_connect.pp
  spec/classes/mod/proxy_connect_spec.rb
Labels: community

#2233 Add support for PassengerPreloadBundler
  manifests/mod/passenger.pp
  manifests/vhost.pp
  spec/acceptance/mod_php_spec.rb
  spec/classes/mod/passenger_spec.rb
  spec/defines/vhost_spec.rb
  templates/mod/passenger.conf.erb
  templates/vhost/_directories.erb
  templates/vhost/_passenger.erb
Labels: feature, community

#2202 Remove warnings and plans to change vhost default naming
  manifests/vhost.pp
  spec/acceptance/vhost_spec.rb
Labels: backwards-incompatible, community

#2234 pdksync - (Maint) PDK Update
  .github/workflows/nightly.yml
  .github/workflows/spec.yml
  .puppet-lint.rc
  .sync.yml
  Rakefile
  manifests/mod/ldap.pp
  manifests/mod/security.pp
  manifests/vhost.pp
  metadata.json
  spec/acceptance/vhost_spec.rb
Labels: maintenance
