Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-08, with the labels that each got.

#2271 Remove duplicate SecDefaultAction in CRS template
  templates/mod/security_crs.conf.erb
Labels: bugfix, community

#2270 Allow configuring CRS paranoia level
  manifests/mod/security.pp
  spec/classes/mod/security_spec.rb
  templates/mod/security_crs.conf.erb
Labels: feature, needs-tests, community

#2275 Allow vhosts to have a string priority again
  manifests/vhost.pp
  manifests/vhost/custom.pp
  manifests/vhost/fragment.pp
  manifests/vhost/proxy.pp
  spec/type_aliases/vhost_priority_spec.rb
  types/vhost/priority.pp
Labels: community

#2272 Allow configuring SecRequestBodyAccess and SecResponseBodyAccess
  manifests/mod/security.pp
  spec/classes/mod/security_spec.rb
  templates/mod/security.conf.erb
Labels: feature, needs-tests, community

#2273 Allow overriding CRS anomaly threshold per vhost
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
  templates/vhost/_security.erb
Labels: feature, needs-tests, community

#2274 Allow overriding CRS allowed HTTP methods per vhost
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
  templates/vhost/_security.erb
Labels: feature, community

#2277 Disable mod_php on EL9
  manifests/mod/php.pp
  manifests/params.pp
  spec/acceptance/mod_php_spec.rb
  spec/classes/mod/php_spec.rb
Labels: bugfix, community

#2282 Release prep v8.0.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#2287 fix duplicate definition of auth_basic-mod
  manifests/default_mods.pp
Labels: bugfix, community

#2284 Allow custom_config to have a string priority again
  manifests/custom_config.pp
Labels: bugfix, community

#2281 Remove auth_kerb and nss from Debian Bullseye
  manifests/params.pp
  spec/classes/mod/auth_kerb_spec.rb
  spec/spec_helper_local.rb
Labels: community

#2283 Manage DNF module for mod_auth_openidc
  manifests/mod/auth_basic.pp
  manifests/mod/auth_cas.pp
  manifests/mod/auth_mellon.pp
  manifests/mod/auth_openidc.pp
  manifests/vhost.pp
  spec/acceptance/auth_openidc_spec.rb
  spec/classes/mod/auth_cas_spec.rb
  spec/classes/mod/auth_gssapi_spec.rb
  spec/classes/mod/auth_kerb_spec.rb
  spec/classes/mod/auth_mellon_spec.rb
  spec/classes/mod/auth_openidc_spec.rb
Labels: feature, community

#2292 Allow setting icons_path to false so no alias will be set for it
  manifests/mod/alias.pp
  spec/classes/mod/alias_spec.rb
Labels: bugfix, community

#2294 Allow integers for timeouts
  manifests/mod/auth_cas.pp
  manifests/mod/proxy.pp
  spec/classes/mod/auth_cas_spec.rb
  spec/classes/mod/proxy_spec.rb
Labels: bugfix, community

#2276 pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04
  manifests/mod/php.pp
  manifests/params.pp
  metadata.json
  spec/acceptance/mod_php_spec.rb
  spec/classes/mod/php_spec.rb
Labels: feature

#2289 Add support for all proxy schemes, not just https://
  manifests/balancermember.pp
  spec/type_aliases/modproxy_spec.rb
  types/modproxyprotocol.pp
Labels: community
