Repository puppetlabs/puppetlabs-apache, pull requests merged in 2022-03, with the labels that each got.

#2220 pdksync - (GH-iac-334) Remove Support for Ubuntu 16.04
  metadata.json
Labels: bugfix

#2216 Drop Apache 2.2 support with Gentoo
  manifests/init.pp
  spec/spec_helper_acceptance_local.rb
Labels: community

#2223 (GH-iac-334) Remove code specific to unsupported OSs
  .github/workflows/spec.yml
  README.md
  manifests/mod/fastcgi.pp
  manifests/mod/security.pp
  manifests/mpm.pp
  manifests/params.pp
  spec/acceptance/mod_php_spec.rb
  spec/classes/mod/php_spec.rb
  spec/spec_helper_acceptance_local.rb
  spec/util/apache_mod_platform_compatibility_spec.rb
Labels: backwards-incompatible

#2224 pdksync - Add labeller and stale GHA workflows
  .github/workflows/labeller.yml
  .github/workflows/stale.yml
Labels: maintenance
