Repository puppetlabs/puppetlabs-apache, pull requests merged in 2023-09, with the labels that each got.

#2447 pdksync - (CAT-1366) - fFix issue url from old jira to github
  metadata.json
Labels: maintenance

#2449 (CAT-1348)-Conversion of erb to epp templates except mod or vhost dir…
  manifests/confd/no_accf.pp
  manifests/fastcgi/server.pp
  manifests/init.pp
  manifests/listen.pp
  manifests/namevirtualhost.pp
  manifests/params.pp
  readmes/README_ja_JP.md
  spec/acceptance/apache_parameters_spec.rb
  spec/classes/apache_spec.rb
  spec/fixtures/site_apache/templates/fake.conf.epp
  templates/confd/no-accf.conf.epp
  templates/fastcgi/server.epp
  templates/httpd.conf.epp
  templates/httpd.conf.erb
  templates/listen.epp
  templates/namevirtualhost.epp
  templates/ports_header.epp
Labels: bugfix

#2457 Simplify data types and array handling
  manifests/mod/remoteip.pp
  templates/mod/remoteip.conf.epp
Labels: feature, community

#2458 Fix remoteip data types
  manifests/mod/remoteip.pp
Labels: maintenance, community

#2403 Add required package for kerberos auth on jammy
  manifests/params.pp
Labels: community

#2459 (CAT-1308) Making mod list more restrictive and minor improvements in documentation for default mods override
  REFERENCE.md
  manifests/default_mods.pp
  manifests/init.pp
Labels: bugfix

#2404 Add the missing mod_authnz_ldap parameters
  templates/vhost/_directories.erb
Labels: feature, community

#2444 Raise Puppet lower bound to >= 7.9.0
  metadata.json
Labels: backwards-incompatible, community

#2397 strickter loglevel syntax verification
  spec/type_aliases/loglevel_spec.rb
  types/loglevel.pp
Labels: bugfix, community

#2460 (CAT-1417) Nested require support for authz_core mod
  .rubocop_todo.yml
  README.md
  REFERENCE.md
  lib/puppet/functions/apache/authz_core_config.rb
  manifests/default_mods.pp
  manifests/mod/authz_core.pp
  manifests/vhost.pp
  spec/functions/authz_core_config_spec.rb
  templates/vhost/_authz_core.epp
  templates/vhost/_directories.erb
Labels: feature

#2439 feat: add Debian12 Compability
  manifests/params.pp
  metadata.json
  spec/acceptance/mod_php_spec.rb
  spec/classes/mod/php_spec.rb
Labels: feature, community, experimental

#2462 (CAT-1424)-Removal of redhat/scientific/oraclelinux 6 for apache module
  spec/acceptance/itk_spec.rb
  spec/classes/mod/lbmethod_bybusyness.rb
  spec/classes/mod/lbmethod_byrequests.rb
  spec/classes/mod/lbmethod_bytraffic.rb
  spec/classes/mod/lbmethod_heartbeat.rb
  spec/defines/vhost_spec.rb
  spec/util/apache_mod_platform_compatibility_spec.rb
Labels: backwards-incompatible

#2467 Inline template without variables
  manifests/vhost.pp
  templates/vhost/_serversignature.erb
Labels: maintenance, community

#2466 Remove deprecated classes
  manifests/mod/dev.pp
  manifests/php.pp
  manifests/proxy.pp
  manifests/python.pp
  manifests/ssl.pp
  spec/classes/mod/dev_spec.rb
Labels: backwards-incompatible, community

#2465 Remove deprecated parameters from mod::userdir
  manifests/mod/userdir.pp
  spec/classes/mod/userdir_spec.rb
  templates/mod/userdir.conf.epp
Labels: backwards-incompatible, community

#2468 (MAINT) - Updating REFERENCE.md
  REFERENCE.md
Labels: maintenance

#2470 (CAT-1449) - Remove deprecated parameters for scriptaliases & passenger
  REFERENCE.md
  manifests/init.pp
  manifests/mod/passenger.pp
  manifests/vhost.pp
  spec/acceptance/vhost_spec.rb
  spec/classes/mod/passenger_spec.rb
  spec/defines/vhost_spec.rb
  templates/mod/passenger.conf.epp
  templates/vhost/_scriptalias.erb
Labels: backwards-incompatible

#2471 (CAT-1450) - Added new parameters for passenger mod
  REFERENCE.md
  manifests/mod/passenger.pp
  manifests/vhost.pp
  spec/classes/mod/passenger_spec.rb
  templates/mod/passenger.conf.epp
Labels: feature

#2473 (CAT-1451) - Fixing nil check fix for SSL config
  templates/mod/ssl.conf.epp
Labels: bugfix

#2477 Update issue link in ReadMe and metadata
  README.md
  spec/util/_resources/test_metadata_json.rb
Labels: maintenance

#2451 CAT-1347 erb to epp conversion
  manifests/vhost.pp
  templates/vhost/_action.epp
  templates/vhost/_action.erb
  templates/vhost/_aliases.epp
  templates/vhost/_aliases.erb
  templates/vhost/_allow_encoded_slashes.epp
  templates/vhost/_allow_encoded_slashes.erb
  templates/vhost/_auth_cas.epp
  templates/vhost/_auth_cas.erb
  templates/vhost/_charsets.epp
  templates/vhost/_charsets.erb
  templates/vhost/_custom_fragment.epp
  templates/vhost/_custom_fragment.erb
  templates/vhost/_docroot.epp
  templates/vhost/_docroot.erb
  templates/vhost/_fallbackresource.epp
  templates/vhost/_fallbackresource.erb
  templates/vhost/_file_footer.epp
  templates/vhost/_file_footer.erb
  templates/vhost/_file_header.epp
  templates/vhost/_file_header.erb
  templates/vhost/_filters.epp
  templates/vhost/_filters.erb
  templates/vhost/_header.epp
  templates/vhost/_header.erb
  templates/vhost/_http2.epp
  templates/vhost/_http2.erb
  templates/vhost/_http_protocol_options.epp
  templates/vhost/_http_protocol_options.erb
  templates/vhost/_itk.epp
  templates/vhost/_itk.erb
  templates/vhost/_jk_mounts.epp
  templates/vhost/_jk_mounts.erb
  templates/vhost/_keepalive_options.epp
  templates/vhost/_keepalive_options.erb
  templates/vhost/_logging.epp
  templates/vhost/_logging.erb
  templates/vhost/_passenger.epp
  templates/vhost/_passenger.erb
  templates/vhost/_requestheader.epp
  templates/vhost/_requestheader.erb
  templates/vhost/_scriptalias.epp
  templates/vhost/_security.epp
  templates/vhost/_security.erb
  templates/vhost/_serveralias.epp
  templates/vhost/_serveralias.erb
  templates/vhost/_shib.epp
  templates/vhost/_shib.erb
  templates/vhost/_sslproxy.epp
  templates/vhost/_sslproxy.erb
  templates/vhost/_suexec.epp
  templates/vhost/_suexec.erb
  templates/vhost/_use_canonical_name.erb
  templates/vhost/_userdir.epp
  templates/vhost/_userdir.erb
  templates/vhost/_wsgi.epp
  templates/vhost/_wsgi.erb
Labels: maintenance
