Repository puppetlabs/puppetlabs-apache, pull requests merged in 2023-06, with the labels that each got.

#2419 (CONT-577) - allow deferred function for password/secret
  manifests/vhost.pp
  templates/vhost/_auth_kerb.epp
  templates/vhost/_auth_kerb.erb
  templates/vhost/_auth_oidc.epp
  templates/vhost/_auth_oidc.erb
Labels: feature

#2414 Update CODEOWNERS
  CODEOWNERS
Labels: maintenance

#2415 use a dedicated Enum type for On/Off and accept lower case too
  manifests/init.pp
  manifests/mod/dumpio.pp
  manifests/mod/md.pp
  manifests/mod/passenger.pp
  manifests/mod/peruser.pp
  manifests/mod/security.pp
  manifests/mod/ssl.pp
  manifests/mod/status.pp
  manifests/vhost.pp
  spec/classes/apache_spec.rb
  types/onoff.pp
Labels: feature, community

#2426 puppetlabs/concat: Allow 9.x
  metadata.json
Labels: community

#2428 (Maint) Addressing Selinux legacy facts
  spec/acceptance/apache_parameters_spec.rb
  spec/acceptance/class_spec.rb
  spec/acceptance/vhost_spec.rb
  spec/setup_acceptance_node.pp
Labels: maintenance

#2393 Add mod_proxy_http2 support
  manifests/mod/proxy_http2.pp
  manifests/vhost.pp
  manifests/vhost/proxy.pp
  spec/classes/mod/proxy_http2_spec.rb
  spec/classes/mod/proxy_http_spec.rb
  spec/defines/vhost_proxy_spec.rb
Labels: feature, community

#2429 (MAINT) Enable legacy SP3 repository for SUSE
  manifests/mod/php.pp
  spec/setup_acceptance_node.pp
Labels: maintenance
