Repository puppetlabs/puppetlabs-apache, pull requests merged in 2023-12, with the labels that each got.

#2501 (CAT-1608) - PDK update
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  metadata.json
  spec/classes/mod/jk_spec.rb
  spec/defines/vhost_spec.rb
  spec/spec_helper.rb
Labels: maintenance

#2507 vhost::directories: switch default from undef to empty array
  REFERENCE.md
  manifests/vhost.pp
Labels: feature, community

#2511 pdksync - (MAINT) PDK Update
  .sync.yml
  Gemfile
  Rakefile
  metadata.json
Labels: maintenance

#2495 Fix `mod_suexec` configuration
  manifests/vhost.pp
  templates/vhost/_suexec.epp
Labels: bugfix, community
