Repository puppetlabs/puppetlabs-apache, pull requests merged in 2023-10, with the labels that each got.

#2479 Drop EoL Debian 9 and older code
  REFERENCE.md
  manifests/mod/apreq2.pp
  manifests/mod/md.pp
  manifests/mod/shib.pp
  manifests/params.pp
  spec/acceptance/vhost_spec.rb
  spec/classes/mod/php_spec.rb
  spec/classes/mod/security_spec.rb
Labels: community

#2480 Remove outdated parameter documentation for ssl_mutex
  REFERENCE.md
  manifests/mod/ssl.pp
Labels: community

#2481 Drop EoL Ubuntu code
  REFERENCE.md
  manifests/mod/md.pp
  spec/classes/mod/php_spec.rb
  spec/classes/mod/security_spec.rb
  spec/defines/vhost_spec.rb
Labels: community

#2488 Remove unused file templates/mod/mpm_event.conf.epp
  templates/mod/mpm_event.conf.epp
Labels: community

#2486 Add AllowOverrideList support
  templates/vhost/_directories.erb
Labels: feature, community

#2491 (MAINT) Fixing apache CI pipeline fix (removing unsupported OS)
  metadata.json
Labels: maintenance
