Repository puppetlabs/puppetlabs-apache, pull requests merged in 2023-07, with the labels that each got.

#2434 (maint) - remove legacy default facts
  .gitignore
  .pdkignore
  Gemfile
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#2435 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#2423 Add MellonSetEnv support
  spec/defines/vhost_spec.rb
  templates/vhost/_directories.erb
Labels: feature, community

#2437 (CAT-1261)-update_SUSE_repo_name
  manifests/mod/php.pp
  spec/setup_acceptance_node.pp
Labels: bugfix
