Repository puppetlabs/puppetlabs-apache, pull requests merged in 2023-01, with the labels that each got.

#2366 Simplify templates by reusing bool2httpd
  templates/mod/authnz_ldap.conf.erb
  templates/mod/rpaf.conf.erb
  templates/vhost/_proxy.erb
Labels: community

#2365 vhost: Make ProxyAddHeaders configureable
  manifests/vhost.pp
  spec/defines/vhost_spec.rb
  templates/vhost/_proxy.erb
Labels: feature, community

#2367 (MAINT) Replace IAC Team with CAT Team
  README.md
Labels: maintenance

#2344 Simplify templates by reusing methods
  templates/mod/ext_filter.conf.erb
  templates/vhost/_directories.erb
  templates/vhost/_proxy.erb
  templates/vhost/_wsgi.erb
Labels: community

#2373 security{,_crs}.conf: switch to structured facts
  spec/classes/mod/security_spec.rb
  templates/mod/security.conf.erb
  templates/mod/security_crs.conf.erb
Labels: bugfix, community

#2372 (#2371) security.conf: Test for SecTmpDir
  spec/classes/mod/security_spec.rb
Labels: community

#2376 (MAINT) - update pdk release image
  .github/workflows/auto_release.yml
Labels: maintenance
