Repository puppetlabs/puppetlabs-apache, pull requests merged in 2023-02, with the labels that each got.

#2378 pdksync - (CONT-211) Adding mend config
  .github/workflows/mend.yml
Labels: maintenance

#2381 (BugFix) Update OS Family comparison to correctly match
  spec/classes/mod/security_spec.rb
  templates/mod/security_crs.conf.erb
Labels: bugfix

#2380 Adding mod_version module to be activated by default
  manifests/default_mods.pp
  manifests/mod/version.pp
Labels: bugfix, community

#2368 Suppress bad Directory comment when DocumentRoot is not set
  templates/vhost/_directories.erb
Labels: community

#2387 (BUGFIX) Update to ensure correct facter comparisons
  manifests/default_confd_files.pp
  manifests/default_mods.pp
  manifests/init.pp
  manifests/mod.pp
  manifests/mod/cgid.pp
  manifests/mod/dav_fs.pp
  manifests/mod/disk_cache.pp
  manifests/mod/event.pp
  manifests/mod/itk.pp
  manifests/mod/peruser.pp
  manifests/mod/prefork.pp
  manifests/mod/ssl.pp
  manifests/mod/version.pp
  manifests/mod/worker.pp
  manifests/mpm.pp
Labels: bugfix

#2385 Fixes mod::proxy allow_from parameter inconsistency #2352
  REFERENCE.md
  manifests/mod/proxy.pp
  templates/mod/proxy.conf.erb
Labels: bugfix, community

#2384 Fix example code for apache::vhost::php_values
  REFERENCE.md
  manifests/vhost.pp
Labels: bugfix, community

#2330 fix rewrite rules being ignored
  spec/defines/vhost_spec.rb
  templates/vhost/_rewrite.erb
Labels: bugfix, community
