Repository puppetlabs/puppetlabs-apache, pull requests merged in 2024-04, with the labels that each got.

#2526 Stop managing mime support package on Debian
  manifests/mod/mime.pp
  manifests/params.pp
Labels: community

#2538 pdksync - update mend to work on cron
  .github/workflows/mend.yml
Labels: maintenance

#2540 Add missing brackets for function call
  spec/acceptance/vhost_spec.rb
  spec/defines/vhost_spec.rb
  templates/vhost/_directories.erb
Labels: bugfix, community

#2535 Add EnableSendfile per directory
  spec/defines/vhost_spec.rb
  templates/vhost/_directories.erb
Labels: community
